チャレンジ課題1 〜 5を提出
shinichiowada/furiPHP_exercise pull request #1
Opened 2021-03-10 15:16 UTC by shinichiowada

チャレンジ課題1 〜 5完了。

2021-03-10 21:47 UTC, kazu-taka requested changes
@shinichiowada 
全体的にコード綺麗で見やすかったです😊
指摘箇所の修正をお願いします✨

2021-03-10 21:47 UTC, kazu-taka commented on .vscode/settings.json
> +}
@shinichiowada 
このファイルはバクさんの設定ファイルになるので、共同開発の時は入れない方がいいので、.gitignoreに以下の内容を追加してから、[ここ](https://qiita.com/ytkt/items/a2afd6be8e4f06c1ea25#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E6%AE%8B%E3%81%97%E3%81%9F%E3%81%84%E3%81%A8%E3%81%8D)のコマンドを実行してみて下さい！(`git rm --cached .vscode/settings.json`)

```bash
.vscode/settings.json
```
```

試したわけではないので、うまくいかない時は連絡下さい✨

2021-03-10 21:47 UTC, kazu-taka commented on challenge1_1.php
> +echo $date->format("現在時刻" . ":" .  "H時i分s秒");
@shinichiowada 
php.iniファイルでタイムゾーンを指定しているので、timezone_setは不要です！

```ini
[Date]
date.timezone = "Asia/Tokyo"
```

問題の内容が **「date関数を利用して、以下の形式で現在の時刻を表示させるプログラムを作成して下さい。」** となっているので、PHPのdate関数を使って実現するよう修正お願いします:bow:

2021-03-10 21:47 UTC, kazu-taka commented on challenge1_3.php
> +$all_teams = [$team_a, $team_b, $team_c];
@shinichiowada 
うまく伝わってなかったかもしれませんが、上記の配列を使って頂きたいので、以下の配列は不要になります🙏

```php
$teams = [
    ["勇者", "戦士", "魔法使い"],
    ["盗賊", "忍者", "商人"],
    ["スライム", "ドラゴン", "魔王"],
];
```

2021-03-10 21:47 UTC, kazu-taka commented on challenge1_func.php
> +
@shinichiowada 
ここの空行はなくても大丈夫です！！

2021-03-10 21:47 UTC, kazu-taka commented on challenge1_5.php
> +            }
@shinichiowada 
ここの条件分岐だと、ダメージが2000以上の時にhpが減らないようになっているので、フローチャートのように
、「ダメージが2000以上か」と「HP - 攻撃力が > 2000か」の条件分岐はまったく別物として考えるようにして下さい✨
(それぞれ独立したifになるということです)

2021-03-10 21:47 UTC, kazu-taka commented on challenge1_5.php
> +            exit;
@shinichiowada 
フローチャートの矢印を見ると、攻撃のループに戻っています。
exitしてしまうと処理が終了してしまうので、exitは不要です👍

2021-03-10 21:47 UTC, kazu-taka commented on challenge1_5.php
> +$attacks = [1 => "剣", 2 => "魔法", 3 => "打撃"];
@shinichiowada 
連想配列はメッセージを出すところでしか使用していないので、無理に連想配列にせずにそのままメッセージを出してもOKです🙆‍♂️
連想配列を使用しなければ、`echo "攻撃技は？" . PHP_EOL . "1.剣 2.魔法 3.打撃" . PHP_EOL;`の1行だけで済んでしまうので✨

2021-03-10 21:47 UTC, kazu-taka commented on challenge1_5.php
> +$attacks = [1 => "剣", 2 => "魔法", 3 => "打撃"];
今回はこのままでOKです！！

2021-03-10 21:47 UTC, kazu-taka commented on challenge1_5.php
> +            }
@shinichiowada 
`($hp = 0);`の()は不要です👍

2021-03-12 15:24 UTC, shinichiowada commented on .vscode/settings.json
> +}
上記の内容通り、実行しました。

2021-03-12 15:25 UTC, shinichiowada commented on challenge1_1.php
> +echo $date->format("現在時刻" . ":" .  "H時i分s秒");
PHPのdate関数を利用して修正しました。

2021-03-12 15:26 UTC, shinichiowada commented on challenge1_3.php
> +$all_teams = [$team_a, $team_b, $team_c];
$teams = の配列を削除し、カリキュラムの配列で動くように修正しました。

2021-03-12 15:27 UTC, shinichiowada commented on challenge1_func.php
> +
行間を詰めました。

2021-03-12 15:28 UTC, shinichiowada commented on challenge1_5.php
> +            }
if文を追加し、()を削除しました。

2021-03-12 15:28 UTC, shinichiowada commented on challenge1_5.php
> +            exit;
exitを削除しました。

2021-03-12 20:34 UTC, kazu-taka requested changes
@shinichiowada 
課題1をdata関数に変更する以外はほとんどOKです👍
再確認お願いします！！

2021-03-12 20:34 UTC, kazu-taka commented on challenge1_1.php
> +echo $date->format('現在時刻:H時i分s秒');
@shinichiowada 
これは`date`関数ではなく、`DateTime`オブジェクトのformatメソッド(関数)を実行しただけになりますので、[`date`](https://www.php.net/manual/ja/function.date.php)関数を使用するように修正お願いします😊

2021-03-12 20:34 UTC, kazu-taka commented on challenge1_3.php
> +        // echo "\n";
@shinichiowada 
今回は問題ないですが、このようなコメントではない残骸等は削除して方が見やすいので、今後の課題に取り組む時は、削除するようにお願いします✨
他の部分も同一です✨

2021-03-12 20:34 UTC, kazu-taka commented on challenge1_5.php
> +    echo "攻撃技は？" . PHP_EOL . "1.剣 2.魔法 3.打撃" . PHP_EOL;
@shinichiowada 
ココは連想配列を使用しないようにしたんですね✨
ということは、上で定義している`$attacks = [1 => "剣", 2 => "魔法", 3 => "打撃"];`は不要になるので、削除お願いします🙏

2021-03-12 20:34 UTC, kazu-taka commented on challenge1_5.php
> +
@shinichiowada 
今回の修正で空行1行増えてしまったようですが、ここは空行が無い方がいいと思います✨
公式マニュアル
https://www.php.net/manual/ja/control-structures.switch.php

2021-03-13 01:47 UTC, shinichiowada commented on challenge1_1.php
> +echo $date->format('現在時刻:H時i分s秒');
date関数で実現するよう修正しました。

2021-03-13 01:48 UTC, shinichiowada commented on challenge1_3.php
> +        // echo "\n";
コメントアウト残骸を削除しました。

2021-03-13 01:48 UTC, shinichiowada commented on challenge1_5.php
> +    echo "攻撃技は？" . PHP_EOL . "1.剣 2.魔法 3.打撃" . PHP_EOL;
連想配列の記述を削除しました。

2021-03-13 01:49 UTC, shinichiowada commented on challenge1_5.php
> +
空行を削除しました。

2021-03-13 03:21 UTC, yukishimizumg reviewed
ほぼOKですが、コメント確認お願いします✨😊

2021-03-13 03:21 UTC, yukishimizumg commented on challenge1_1.php
> +date_default_timezone_set('Asia/Tokyo');
一真さんも書いてますが、
php.iniファイルでタイムゾーンを指定しているので、timezone_setは不要です✨

```
[Date]
date.timezone = "Asia/Tokyo"
```

2021-03-13 03:21 UTC, yukishimizumg commented on challenge1_1.php
> +echo "現在時刻:" .  date("H時i分s秒");
修正不要ですが、`H`を`G` にすると課題と同じように前0なしの時刻を表示できます✨

```php
<?php
echo '現在時刻：' . date('G時i分s秒');
```

2021-03-13 03:21 UTC, yukishimizumg commented on challenge1_3.php
> +
空行不要です✨

2021-03-13 03:21 UTC, yukishimizumg commented on challenge1_3.php
> +
空行不要です✨

2021-03-13 04:45 UTC, shinichiowada commented on challenge1_1.php
> +date_default_timezone_set('Asia/Tokyo');
timezone_setを削除しました。

2021-03-13 04:45 UTC, shinichiowada commented on challenge1_1.php
> +echo "現在時刻:" .  date("H時i分s秒");
date('H時i分s秒') ➡ date('G時i分s秒')に修正。

2021-03-13 04:46 UTC, shinichiowada commented on challenge1_3.php
> +
空行を削除しました。

2021-03-13 04:46 UTC, shinichiowada commented on challenge1_3.php
> +
空行を削除しました。

2021-03-13 05:12 UTC, yukishimizumg reviewed
修正ありがとうございます!!
すみません、1つだけ指摘漏れがありましたので、そこだけ対応お願いします🙇💦
それを修正いただいたらマージしてOKです✨

2021-03-13 05:12 UTC, yukishimizumg commented on challenge1_func.php
> +    EOM;
ヒアドキュメントの2行目以降はインデントしないようにしましょう✨

```php
function createMsg($member, $enemy, $damage)
{
    $msg = <<< EOM
{$member}は,
{$enemy}に攻撃した。
クリティカルヒット!!
{$enemy}は,{$damage}のダメージを受けた。\n
EOM;
    echo $msg;
}
```

2021-03-13 05:15 UTC, yukishimizumg commented on challenge1_func.php
> +    $msg = <<< EOM
`<<<` と `EOM` の間のスペースを削除してください✨

```php
function createMsg($member, $enemy, $damage)
{
    $msg = <<<EOM
{$member}は,
{$enemy}に攻撃した。
クリティカルヒット!!
{$enemy}は,{$damage}のダメージを受けた。\n
EOM;
    echo $msg;
}
```

2021-03-13 06:06 UTC, shinichiowada commented on challenge1_func.php
> +    $msg = <<< EOM
<<< EOM ➡ <<<EOM間を詰めました。

2021-03-13 06:06 UTC, shinichiowada commented
課題1〜5の修正完了、マージします😊

2021-03-13 06:07 UTC, merged